//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment10Ques.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpBo1", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAPI")]
    [System.SerializableAttribute()]
    public partial class EmpBo1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAPI")]
    [System.SerializableAttribute()]
    public partial class ExecClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        EmployeeBO.EmpBO[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<EmployeeBO.EmpBO[]> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataJson", ReplyAction="http://tempuri.org/IService1/GetDataJsonResponse")]
        EmployeeBO.EmpBO[] GetDataJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataJson", ReplyAction="http://tempuri.org/IService1/GetDataJsonResponse")]
        System.Threading.Tasks.Task<EmployeeBO.EmpBO[]> GetDataJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataCont", ReplyAction="http://tempuri.org/IService1/DataContResponse")]
        Assignment10Ques.ServiceReference2.EmpBo1[] DataCont();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataCont", ReplyAction="http://tempuri.org/IService1/DataContResponse")]
        System.Threading.Tasks.Task<Assignment10Ques.ServiceReference2.EmpBo1[]> DataContAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataCont1", ReplyAction="http://tempuri.org/IService1/DataCont1Response")]
        string DataCont1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataCont1", ReplyAction="http://tempuri.org/IService1/DataCont1Response")]
        System.Threading.Tasks.Task<string> DataCont1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FaultCont", ReplyAction="http://tempuri.org/IService1/FaultContResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Assignment10Ques.ServiceReference2.ExecClass), Action="http://tempuri.org/IService1/FaultContExecClassFault", Name="ExecClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAPI")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EmployeeBO.EmpBO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EmployeeBO.EmpBO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Assignment10Ques.ServiceReference2.EmpBo1[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Assignment10Ques.ServiceReference2.EmpBo1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Assignment10Ques.ServiceReference2.ExecClass))]
        object FaultCont();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FaultCont", ReplyAction="http://tempuri.org/IService1/FaultContResponse")]
        System.Threading.Tasks.Task<object> FaultContAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Method1", ReplyAction="http://tempuri.org/IService1/Method1Response")]
        int Method1(int param1, int param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Method1", ReplyAction="http://tempuri.org/IService1/Method1Response")]
        System.Threading.Tasks.Task<int> Method1Async(int param1, int param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Method2", ReplyAction="http://tempuri.org/IService1/Method2Response")]
        int Method2(int param1, int param2, int param3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Method2", ReplyAction="http://tempuri.org/IService1/Method2Response")]
        System.Threading.Tasks.Task<int> Method2Async(int param1, int param2, int param3);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Assignment10Ques.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Assignment10Ques.ServiceReference2.IService1>, Assignment10Ques.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmployeeBO.EmpBO[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<EmployeeBO.EmpBO[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public EmployeeBO.EmpBO[] GetDataJson() {
            return base.Channel.GetDataJson();
        }
        
        public System.Threading.Tasks.Task<EmployeeBO.EmpBO[]> GetDataJsonAsync() {
            return base.Channel.GetDataJsonAsync();
        }
        
        public Assignment10Ques.ServiceReference2.EmpBo1[] DataCont() {
            return base.Channel.DataCont();
        }
        
        public System.Threading.Tasks.Task<Assignment10Ques.ServiceReference2.EmpBo1[]> DataContAsync() {
            return base.Channel.DataContAsync();
        }
        
        public string DataCont1() {
            return base.Channel.DataCont1();
        }
        
        public System.Threading.Tasks.Task<string> DataCont1Async() {
            return base.Channel.DataCont1Async();
        }
        
        public object FaultCont() {
            return base.Channel.FaultCont();
        }
        
        public System.Threading.Tasks.Task<object> FaultContAsync() {
            return base.Channel.FaultContAsync();
        }
        
        public int Method1(int param1, int param2) {
            return base.Channel.Method1(param1, param2);
        }
        
        public System.Threading.Tasks.Task<int> Method1Async(int param1, int param2) {
            return base.Channel.Method1Async(param1, param2);
        }
        
        public int Method2(int param1, int param2, int param3) {
            return base.Channel.Method2(param1, param2, param3);
        }
        
        public System.Threading.Tasks.Task<int> Method2Async(int param1, int param2, int param3) {
            return base.Channel.Method2Async(param1, param2, param3);
        }
    }
}
