//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment10Ques.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceAppSoap")]
    public interface ServiceAppSoap {
        
        // CODEGEN: Generating message contract since message GetMonthRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment10Ques.ServiceReference1.GetMonthResponse GetMonth(Assignment10Ques.ServiceReference1.GetMonthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonth", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.GetMonthResponse> GetMonthAsync(Assignment10Ques.ServiceReference1.GetMonthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonthNoAuthentication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment10Ques.ServiceReference1.Months[] GetMonthNoAuthentication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonthNoAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.Months[]> GetMonthNoAuthenticationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment10Ques.ServiceReference1.EmpBO[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.EmpBO[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Assignment10Ques.ServiceReference1.CountryList[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.CountryList[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal Calculte(Assignment10Ques.ServiceReference1.Calc cal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculte", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalculteAsync(Assignment10Ques.ServiceReference1.Calc cal);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Calc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int num1Field;
        
        private int num2Field;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Num1 {
            get {
                return this.num1Field;
            }
            set {
                this.num1Field = value;
                this.RaisePropertyChanged("Num1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Num2 {
            get {
                return this.num2Field;
            }
            set {
                this.num2Field = value;
                this.RaisePropertyChanged("Num2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CountryList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmpBO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int ageField;
        
        private System.DateTime joiningDateField;
        
        private int salaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime JoiningDate {
            get {
                return this.joiningDateField;
            }
            set {
                this.joiningDateField = value;
                this.RaisePropertyChanged("JoiningDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
                this.RaisePropertyChanged("Salary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Months : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMonth", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMonthRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Assignment10Ques.ServiceReference1.AuthHeader AuthHeader;
        
        public GetMonthRequest() {
        }
        
        public GetMonthRequest(Assignment10Ques.ServiceReference1.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMonthResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMonthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object GetMonthResult;
        
        public GetMonthResponse() {
        }
        
        public GetMonthResponse(object GetMonthResult) {
            this.GetMonthResult = GetMonthResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAppSoapChannel : Assignment10Ques.ServiceReference1.ServiceAppSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAppSoapClient : System.ServiceModel.ClientBase<Assignment10Ques.ServiceReference1.ServiceAppSoap>, Assignment10Ques.ServiceReference1.ServiceAppSoap {
        
        public ServiceAppSoapClient() {
        }
        
        public ServiceAppSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAppSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAppSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAppSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment10Ques.ServiceReference1.GetMonthResponse Assignment10Ques.ServiceReference1.ServiceAppSoap.GetMonth(Assignment10Ques.ServiceReference1.GetMonthRequest request) {
            return base.Channel.GetMonth(request);
        }
        
        public object GetMonth(Assignment10Ques.ServiceReference1.AuthHeader AuthHeader) {
            Assignment10Ques.ServiceReference1.GetMonthRequest inValue = new Assignment10Ques.ServiceReference1.GetMonthRequest();
            inValue.AuthHeader = AuthHeader;
            Assignment10Ques.ServiceReference1.GetMonthResponse retVal = ((Assignment10Ques.ServiceReference1.ServiceAppSoap)(this)).GetMonth(inValue);
            return retVal.GetMonthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.GetMonthResponse> Assignment10Ques.ServiceReference1.ServiceAppSoap.GetMonthAsync(Assignment10Ques.ServiceReference1.GetMonthRequest request) {
            return base.Channel.GetMonthAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.GetMonthResponse> GetMonthAsync(Assignment10Ques.ServiceReference1.AuthHeader AuthHeader) {
            Assignment10Ques.ServiceReference1.GetMonthRequest inValue = new Assignment10Ques.ServiceReference1.GetMonthRequest();
            inValue.AuthHeader = AuthHeader;
            return ((Assignment10Ques.ServiceReference1.ServiceAppSoap)(this)).GetMonthAsync(inValue);
        }
        
        public Assignment10Ques.ServiceReference1.Months[] GetMonthNoAuthentication() {
            return base.Channel.GetMonthNoAuthentication();
        }
        
        public System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.Months[]> GetMonthNoAuthenticationAsync() {
            return base.Channel.GetMonthNoAuthenticationAsync();
        }
        
        public Assignment10Ques.ServiceReference1.EmpBO[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.EmpBO[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public Assignment10Ques.ServiceReference1.CountryList[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<Assignment10Ques.ServiceReference1.CountryList[]> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public decimal Calculte(Assignment10Ques.ServiceReference1.Calc cal) {
            return base.Channel.Calculte(cal);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculteAsync(Assignment10Ques.ServiceReference1.Calc cal) {
            return base.Channel.CalculteAsync(cal);
        }
    }
}
